#!/usr/bin/expect -f
set timeout -1
set password "eCTyD*R.94zTba"
spawn scp -o StrictHostKeyChecking=no /Users/valeriiguro/Desktop/AVATARv1.0/setup_vps.sh /Users/valeriiguro/Desktop/AVATARv1.0/nginx_avatar.conf /Users/valeriiguro/Desktop/AVATARv1.0/avatar-backend.service /Users/valeriiguro/Desktop/AVATARv1.0/avatar-bot.service root@103.74.92.72:/root/
expect {
    "*assword:*" { send "$password\r"; exp_continue }
    eof
}
