"""fix_sync_session_schema_detailed

Revision ID: 0dc17d3402e3
Revises: c232dc0e084d
Create Date: 2026-03-09 19:11:15.691784

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0dc17d3402e3'
down_revision: Union[str, None] = 'c232dc0e084d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_images_archetype")
    op.execute("DROP TABLE IF EXISTS images CASCADE")
    op.execute("DROP TABLE IF EXISTS image_stats CASCADE")
    op.execute("DROP TABLE IF EXISTS visual_diagnostic_sessions CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_image_interactions_image_id")
    op.execute("DROP INDEX IF EXISTS ix_image_interactions_session_id")
    op.execute("DROP INDEX IF EXISTS ix_image_interactions_user_id")
    op.execute("DROP TABLE IF EXISTS image_interactions CASCADE")
    op.execute("DROP TABLE IF EXISTS generation_metadata CASCADE")
    op.execute("DROP TABLE IF EXISTS visual_stimuli CASCADE")
    op.execute("DROP TABLE IF EXISTS stimulus_images CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_stimulus_sets_session_id")
    op.execute("DROP TABLE IF EXISTS stimulus_sets CASCADE")
    op.execute("DROP TABLE IF EXISTS user_behavioral_profiles CASCADE")
    op.execute("ALTER TABLE IF EXISTS session_features DROP COLUMN IF EXISTS dark_light_bias")
    op.execute("ALTER TABLE IF EXISTS session_features DROP COLUMN IF EXISTS visual_density_preference")
    op.execute("ALTER TABLE IF EXISTS session_features DROP COLUMN IF EXISTS hover_time_mean")
    op.execute("ALTER TABLE IF EXISTS session_features DROP COLUMN IF EXISTS contrast_preference")
    op.execute("ALTER TABLE IF EXISTS session_features DROP COLUMN IF EXISTS image_complexity_preference")
    op.execute("ALTER TABLE IF EXISTS session_features DROP COLUMN IF EXISTS hover_time_variance")
    op.add_column('sync_sessions', sa.Column('mental_thinking', sa.Text(), nullable=True))
    op.add_column('sync_sessions', sa.Column('mental_reactions', sa.Text(), nullable=True))
    op.add_column('sync_sessions', sa.Column('mental_patterns', sa.Text(), nullable=True))
    op.add_column('sync_sessions', sa.Column('mental_aspirations', sa.Text(), nullable=True))
    op.add_column('sync_sessions', sa.Column('recurring_symbol', sa.String(length=256), nullable=True))
    op.add_column('sync_sessions', sa.Column('body_signal', sa.Text(), nullable=True))
    op.add_column('sync_sessions', sa.Column('reaction_pattern', sa.String(length=64), nullable=True))
    op.add_column('sync_sessions', sa.Column('response_delay_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("ALTER TABLE IF EXISTS user_behavior_profile DROP COLUMN IF EXISTS dark_light_bias")
    op.execute("ALTER TABLE IF EXISTS user_behavior_profile DROP COLUMN IF EXISTS visual_complexity_preference")
    op.execute("ALTER TABLE IF EXISTS user_behavior_profile DROP COLUMN IF EXISTS contrast_bias")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_behavior_profile', sa.Column('contrast_bias', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user_behavior_profile', sa.Column('visual_complexity_preference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user_behavior_profile', sa.Column('dark_light_bias', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS response_delay_info")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS reaction_pattern")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS body_signal")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS recurring_symbol")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS mental_aspirations")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS mental_patterns")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS mental_reactions")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS mental_thinking")
    op.add_column('session_features', sa.Column('hover_time_variance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('session_features', sa.Column('image_complexity_preference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('session_features', sa.Column('contrast_preference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('session_features', sa.Column('hover_time_mean', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('session_features', sa.Column('visual_density_preference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('session_features', sa.Column('dark_light_bias', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('user_behavioral_profiles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('preferred_archetypes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('decision_speed_rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.5'), autoincrement=False, nullable=True),
    sa.Column('seen_stimuli_history', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('behavioral_pattern_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_behavioral_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='user_behavioral_profiles_user_id_key')
    )
    op.create_table('stimulus_sets',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('stimulus_sets_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('layout_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='stimulus_sets_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_stimulus_sets_session_id', 'stimulus_sets', ['session_id'], unique=False)
    op.create_table('stimulus_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stimulus_set_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['stimulus_set_id'], ['stimulus_sets.id'], name='stimulus_images_stimulus_set_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stimulus_images_pkey')
    )
    op.create_table('visual_stimuli',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('archetype_category', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('diagnostic_value_score', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('selection_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('view_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('avg_reaction_time_ms', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=True),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='visual_stimuli_pkey')
    )
    op.create_table('generation_metadata',
    sa.Column('image_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prompt_vector', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('archetype', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('symbolic_elements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('composition_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('color_palette', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('contrast_level', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('visual_density', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('diffusion_model', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('seed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('generation_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('image_id', name='generation_metadata_pkey')
    )
    op.create_table('image_interactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hover_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('focus_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('reaction_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cursor_distance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('selected', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='image_interactions_pkey')
    )
    op.create_index('ix_image_interactions_user_id', 'image_interactions', ['user_id'], unique=False)
    op.create_index('ix_image_interactions_session_id', 'image_interactions', ['session_id'], unique=False)
    op.create_index('ix_image_interactions_image_id', 'image_interactions', ['image_id'], unique=False)
    op.create_table('visual_diagnostic_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shown_stimuli_ids', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('selected_stimulus_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reaction_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('context_tag', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='visual_diagnostic_sessions_pkey')
    )
    op.create_table('image_stats',
    sa.Column('image_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('times_shown', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('times_selected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('selection_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_reaction_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('selection_entropy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('diagnostic_power_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('image_id', name='image_stats_pkey')
    )
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('archetype', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('generation_prompt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('seed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_version', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('color_temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('contrast', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('visual_density', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('symbolic_objects', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('complexity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('darkness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('entropy_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('embedding_vector', pgvector.sqlalchemy.vector.VECTOR(dim=512), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    op.create_index('ix_images_archetype', 'images', ['archetype'], unique=False)
    # ### end Alembic commands ###
