"""Add AvatarCard with pgvector

Revision ID: 4082100eff96
Revises: ad7e29bb2558
Create Date: 2026-03-03 23:20:03.803779

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '4082100eff96'
down_revision: Union[str, None] = 'ad7e29bb2558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('sphere', sa.String(), nullable=False),
    sa.Column('shadow', sa.Text(), nullable=False),
    sa.Column('light', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_cards_archetype_id'), 'avatar_cards', ['archetype_id'], unique=False)
    op.create_index(op.f('ix_avatar_cards_id'), 'avatar_cards', ['id'], unique=False)
    op.create_index(op.f('ix_avatar_cards_sphere'), 'avatar_cards', ['sphere'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_avatar_cards_sphere'), table_name='avatar_cards')
    op.drop_index(op.f('ix_avatar_cards_id'), table_name='avatar_cards')
    op.drop_index(op.f('ix_avatar_cards_archetype_id'), table_name='avatar_cards')
    op.drop_table('avatar_cards')
    # ### end Alembic commands ###
