"""add dsb_raw_data table

Revision ID: 76499bd5a45e
Revises: create_dsb_missing
Create Date: 2026-03-25 11:05:54.708678

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '76499bd5a45e'
down_revision: Union[str, None] = 'create_dsb_missing'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dsb_raw_data',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('portrait_id', sa.UUID(), nullable=False),
        sa.Column('system_name', sa.String(length=64), nullable=False),
        sa.Column('data_group', sa.String(length=64), nullable=False),
        sa.Column('data_key', sa.String(length=128), nullable=False),
        sa.Column('payload', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['portrait_id'], ['dsb_digital_portraits.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dsb_raw_data_data_group'), 'dsb_raw_data', ['data_group'], unique=False)
    op.create_index(op.f('ix_dsb_raw_data_data_key'), 'dsb_raw_data', ['data_key'], unique=False)
    op.create_index(op.f('ix_dsb_raw_data_portrait_id'), 'dsb_raw_data', ['portrait_id'], unique=False)
    op.create_index(op.f('ix_dsb_raw_data_system_name'), 'dsb_raw_data', ['system_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dsb_raw_data_system_name'), table_name='dsb_raw_data')
    op.drop_index(op.f('ix_dsb_raw_data_portrait_id'), table_name='dsb_raw_data')
    op.drop_index(op.f('ix_dsb_raw_data_data_key'), table_name='dsb_raw_data')
    op.drop_index(op.f('ix_dsb_raw_data_data_group'), table_name='dsb_raw_data')
    op.drop_table('dsb_raw_data')
    # ### end Alembic commands ###
