"""Add referral fields

Revision ID: 7eb030e2e3ce
Revises: b2c3d4e5f6a7
Create Date: 2026-03-03 15:23:48.236963

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '7eb030e2e3ce'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_code', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('referred_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(f'DROP INDEX IF EXISTS {op.f("ix_users_referral_code")}')
    op.execute("ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS referred_by")
    op.execute("ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS referral_code")
    # ### end Alembic commands ###
