"""increase_hawkins_level_size

Revision ID: 9a56354595a2
Revises: a17dd45bd4cc
Create Date: 2026-02-28 00:54:11.352934

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '9a56354595a2'
down_revision: Union[str, None] = 'a17dd45bd4cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_sessions', 'hawkins_level',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_sessions', 'hawkins_level',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
