"""initial_schema

Revision ID: a17dd45bd4cc
Revises: 
Create Date: 2026-02-25 00:41:13.454303

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a17dd45bd4cc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('birth_time', sa.String(length=8), nullable=True),
    sa.Column('birth_place', sa.String(length=256), nullable=True),
    sa.Column('birth_lat', sa.Float(), nullable=True),
    sa.Column('birth_lon', sa.Float(), nullable=True),
    sa.Column('birth_tz', sa.String(length=64), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('evolution_level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('onboarding_done', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_tg_id'), 'users', ['tg_id'], unique=True)
    op.create_table('card_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('sphere', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_recommended_astro', sa.Boolean(), nullable=False),
    sa.Column('is_recommended_portrait', sa.Boolean(), nullable=False),
    sa.Column('hawkins_current', sa.Integer(), nullable=False),
    sa.Column('hawkins_peak', sa.Integer(), nullable=False),
    sa.Column('hawkins_entry', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('sync_sessions_count', sa.Integer(), nullable=False),
    sa.Column('align_sessions_count', sa.Integer(), nullable=False),
    sa.Column('astro_priority', sa.String(length=16), nullable=True),
    sa.Column('astro_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_progress_user_id'), 'card_progress', ['user_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('archetype_id_1', sa.Integer(), nullable=False),
    sa.Column('sphere_1', sa.String(length=32), nullable=False),
    sa.Column('archetype_id_2', sa.Integer(), nullable=False),
    sa.Column('sphere_2', sa.String(length=32), nullable=False),
    sa.Column('connection_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_user_id'), 'connections', ['user_id'], unique=False)
    op.create_table('daily_reflect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reflect_date', sa.Date(), nullable=False),
    sa.Column('current_emotion', sa.String(length=64), nullable=True),
    sa.Column('hawkins_today', sa.Integer(), nullable=False),
    sa.Column('integration_done', sa.String(length=16), nullable=True),
    sa.Column('focus_sphere', sa.String(length=32), nullable=True),
    sa.Column('energy_awarded', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_reflect_user_id'), 'daily_reflect', ['user_id'], unique=False)
    op.create_table('game_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('titles_unlocked', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('badges_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_title', sa.String(length=64), nullable=False),
    sa.Column('daily_energy', sa.Integer(), nullable=False),
    sa.Column('daily_energy_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id_1', sa.Integer(), nullable=False),
    sa.Column('user_id_2', sa.Integer(), nullable=False),
    sa.Column('sphere', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('chat_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compatibility_score', sa.Integer(), nullable=False),
    sa.Column('match_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id_1'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id_2'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_user_id_1'), 'matches', ['user_id_1'], unique=False)
    op.create_index(op.f('ix_matches_user_id_2'), 'matches', ['user_id_2'], unique=False)
    op.create_table('natal_charts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planets_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aspects_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommended_cards_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ascendant_sign', sa.String(length=32), nullable=True),
    sa.Column('ascendant_ruler', sa.String(length=32), nullable=True),
    sa.Column('stelliums_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('patterns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('cards_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patterns_user_id'), 'patterns', ['user_id'], unique=False)
    op.create_table('user_portrait',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sphere', sa.String(length=32), nullable=False),
    sa.Column('cards_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('patterns_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('body_map_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_hawkins', sa.Integer(), nullable=False),
    sa.Column('min_hawkins', sa.Integer(), nullable=False),
    sa.Column('hawkins_timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_portrait_user_id'), 'user_portrait', ['user_id'], unique=False)
    op.create_table('voice_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.String(length=512), nullable=True),
    sa.Column('transcript', sa.String(length=4096), nullable=True),
    sa.Column('session_type', sa.String(length=32), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_records_user_id'), 'voice_records', ['user_id'], unique=False)
    op.create_table('align_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_progress_id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('sphere', sa.String(length=32), nullable=False),
    sa.Column('hawkins_entry', sa.Integer(), nullable=False),
    sa.Column('hawkins_min', sa.Integer(), nullable=False),
    sa.Column('hawkins_peak', sa.Integer(), nullable=False),
    sa.Column('hawkins_exit', sa.Integer(), nullable=False),
    sa.Column('agent_level_used', sa.Integer(), nullable=False),
    sa.Column('messages_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('integration_plan', sa.Text(), nullable=True),
    sa.Column('stages_completed', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('patterns_identified', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_belief', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_progress_id'], ['card_progress.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_align_sessions_user_id'), 'align_sessions', ['user_id'], unique=False)
    op.create_table('sync_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('card_progress_id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('sphere', sa.String(length=32), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=False),
    sa.Column('is_complete', sa.Boolean(), nullable=False),
    sa.Column('phase_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extracted_core_belief', sa.Text(), nullable=True),
    sa.Column('extracted_shadow_pattern', sa.Text(), nullable=True),
    sa.Column('extracted_body_anchor', sa.Text(), nullable=True),
    sa.Column('extracted_projection', sa.Text(), nullable=True),
    sa.Column('extracted_avoidance', sa.Text(), nullable=True),
    sa.Column('extracted_dominant_emotion', sa.String(length=64), nullable=True),
    sa.Column('extracted_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hawkins_score', sa.Integer(), nullable=False),
    sa.Column('hawkins_level', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_progress_id'], ['card_progress.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_sessions_user_id'), 'sync_sessions', ['user_id'], unique=False)
    op.create_table('diary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('align_session_id', sa.Integer(), nullable=True),
    sa.Column('archetype_id', sa.Integer(), nullable=False),
    sa.Column('sphere', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('voice_url', sa.String(length=512), nullable=True),
    sa.Column('voice_transcript', sa.Text(), nullable=True),
    sa.Column('integration_plan', sa.Text(), nullable=True),
    sa.Column('integration_done', sa.Boolean(), nullable=False),
    sa.Column('integration_done_partially', sa.Boolean(), nullable=False),
    sa.Column('entry_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['align_session_id'], ['align_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_user_id'), 'diary', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diary_user_id'), table_name='diary')
    op.drop_table('diary')
    op.drop_index(op.f('ix_sync_sessions_user_id'), table_name='sync_sessions')
    op.drop_table('sync_sessions')
    op.drop_index(op.f('ix_align_sessions_user_id'), table_name='align_sessions')
    op.drop_table('align_sessions')
    op.drop_index(op.f('ix_voice_records_user_id'), table_name='voice_records')
    op.drop_table('voice_records')
    op.drop_index(op.f('ix_user_portrait_user_id'), table_name='user_portrait')
    op.drop_table('user_portrait')
    op.drop_index(op.f('ix_patterns_user_id'), table_name='patterns')
    op.drop_table('patterns')
    op.drop_table('natal_charts')
    op.drop_index(op.f('ix_matches_user_id_2'), table_name='matches')
    op.drop_index(op.f('ix_matches_user_id_1'), table_name='matches')
    op.drop_table('matches')
    op.drop_table('game_state')
    op.drop_index(op.f('ix_daily_reflect_user_id'), table_name='daily_reflect')
    op.drop_table('daily_reflect')
    op.drop_index(op.f('ix_connections_user_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_card_progress_user_id'), table_name='card_progress')
    op.drop_table('card_progress')
    op.drop_index(op.f('ix_users_tg_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
