"""Add current_phase to ReflectionSession

Revision ID: a535e559fc9f
Revises: c64e65474176
Create Date: 2026-03-12 16:19:50.536550

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a535e559fc9f'
down_revision: Union[str, None] = 'c64e65474176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflection_sessions', sa.Column('current_phase', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reflection_sessions', 'current_phase')
    # ### end Alembic commands ###
