"""Add current_phase to ReflectionSession

Revision ID: a535e559fc9f
Revises: c64e65474176
Create Date: 2026-03-12 16:19:50.536550

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a535e559fc9f'
down_revision: Union[str, None] = 'c64e65474176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE IF EXISTS reflection_sessions ADD COLUMN IF NOT EXISTS current_phase INTEGER DEFAULT 1 NOT NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE IF EXISTS reflection_sessions DROP COLUMN IF EXISTS current_phase")
    # ### end Alembic commands ###
