"""Add sphere_descriptions_json to NatalChart

Revision ID: aa2e4afd897d
Revises: 4082100eff96
Create Date: 2026-03-04 15:08:06.145015

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aa2e4afd897d'
down_revision: Union[str, None] = '4082100eff96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('natal_charts', sa.Column('sphere_descriptions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('natal_charts', 'sphere_descriptions_json')
    # ### end Alembic commands ###
