"""Add recommended_ai to card_progress

Revision ID: ad7e29bb2558
Revises: 7eb030e2e3ce
Create Date: 2026-03-03 19:13:17.664632

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'ad7e29bb2558'
down_revision: Union[str, None] = '7eb030e2e3ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card_progress', sa.Column('is_recommended_ai', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('card_progress', sa.Column('ai_score', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card_progress', 'ai_score')
    op.drop_column('card_progress', 'is_recommended_ai')
    # ### end Alembic commands ###
