"""Add AIDiagnosticSession and milestones_awarded

Revision ID: c232dc0e084d
Revises: aa2e4afd897d
Create Date: 2026-03-04 16:31:37.900479

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c232dc0e084d'
down_revision: Union[str, None] = 'aa2e4afd897d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_diagnostic_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_history_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_recommendations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_diagnostic_sessions_user_id'), 'ai_diagnostic_sessions', ['user_id'], unique=True)
    op.execute("DROP TABLE IF EXISTS sphere_links CASCADE")
    op.execute("DROP TABLE IF EXISTS emotion_tracking CASCADE")
    op.execute("DROP TABLE IF EXISTS user_cards CASCADE")
    op.execute("DROP TABLE IF EXISTS referrals CASCADE")
    op.execute("DROP TABLE IF EXISTS practices CASCADE")
    op.execute("DROP TABLE IF EXISTS token_transactions CASCADE")
    op.execute("DROP TABLE IF EXISTS reflection_messages CASCADE")
    op.execute("DROP TABLE IF EXISTS reflection_sessions CASCADE")
    op.execute("DROP TABLE IF EXISTS user_balance CASCADE")
    op.execute("DROP TABLE IF EXISTS user_feedback CASCADE")
    op.execute("DROP TABLE IF EXISTS quick_notes CASCADE")
    op.alter_column('diary', 'archetype_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('diary', 'sphere',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.add_column('game_state', sa.Column('milestones_awarded', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("ALTER TABLE IF EXISTS natal_charts DROP COLUMN IF EXISTS detailed_reading")
    op.execute("ALTER TABLE IF EXISTS users DROP COLUMN IF EXISTS gender")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('natal_charts', sa.Column('detailed_reading', sa.TEXT(), autoincrement=False, nullable=True))
    op.execute("ALTER TABLE IF EXISTS game_state DROP COLUMN IF EXISTS milestones_awarded")
    op.alter_column('diary', 'sphere',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('diary', 'archetype_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('quick_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('emotion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('emotion_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pattern_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reflection_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='quick_notes_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='quick_notes_pkey')
    )
    op.create_table('user_feedback',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_feedback_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_feedback_pkey')
    )
    op.create_table('user_balance',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), server_default=sa.text('100000'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_balance_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_balance_pkey'),
    sa.UniqueConstraint('user_id', name='user_balance_user_id_key')
    )
    op.create_table('reflection_sessions',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('reflection_sessions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('house', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('archetype', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('sphere', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('entry_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('peak_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='reflection_sessions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reflection_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('reflection_messages',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('reflection_messages_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['reflection_sessions.id'], name='reflection_messages_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reflection_messages_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('token_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('real_cost_cents', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='token_transactions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='token_transactions_pkey')
    )
    op.create_table('practices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sphere', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('archetype', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('practice_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['reflection_sessions.id'], name='practices_session_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='practices_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='practices_pkey')
    )
    op.create_table('referrals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referrer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('referred_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('bonus_amount', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('sessions_completed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unique_days', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('activated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referred_id'], ['users.id'], name='referrals_referred_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], name='referrals_referrer_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='referrals_pkey'),
    sa.UniqueConstraint('referred_id', name='referrals_referred_id_key')
    )
    op.create_table('user_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('house', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sphere', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('archetype', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('weight', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('consecutive_higher', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('consecutive_lower', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_cards_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_cards_pkey')
    )
    op.create_table('emotion_tracking',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detected_emotion', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('emotion_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_lowest', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['reflection_messages.id'], name='emotion_tracking_message_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['reflection_sessions.id'], name='emotion_tracking_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='emotion_tracking_pkey')
    )
    op.create_table('sphere_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('house1', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('house2', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sphere1', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('sphere2', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('link_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('strength', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('meaning', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sphere_links_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sphere_links_pkey')
    )
    op.execute(f'DROP INDEX IF EXISTS {op.f("ix_ai_diagnostic_sessions_user_id")}')
    op.execute("DROP TABLE IF EXISTS ai_diagnostic_sessions CASCADE")
    # ### end Alembic commands ###
