"""add meta_data to text_scene

Revision ID: c64e65474176
Revises: fa8196b23c19
Create Date: 2026-03-11 19:28:07.771753

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c64e65474176'
down_revision: Union[str, None] = 'fa8196b23c19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_scenes', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_scenes', 'meta_data')
    # ### end Alembic commands ###
