"""add_last_energy_claim_to_gamestate

Revision ID: e46b961fd4ac
Revises: a535e559fc9f
Create Date: 2026-03-14 20:30:10.075820

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e46b961fd4ac'
down_revision: Union[str, None] = 'a535e559fc9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_state', sa.Column('last_energy_claim', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_state', 'last_energy_claim')
    # ### end Alembic commands ###
