"""complete_sync_and_diary_schema

Revision ID: fa8196b23c19
Revises: 0dc17d3402e3
Create Date: 2026-03-09 19:49:18.817993

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'fa8196b23c19'
down_revision: Union[str, None] = '0dc17d3402e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_sessions', sa.Column('real_picture', sa.Text(), nullable=True))
    op.add_column('sync_sessions', sa.Column('core_pattern', sa.Text(), nullable=True))
    op.add_column('sync_sessions', sa.Column('shadow_active', sa.Text(), nullable=True))
    op.add_column('sync_sessions', sa.Column('body_anchor', sa.Text(), nullable=True))
    op.add_column('sync_sessions', sa.Column('first_insight', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS first_insight")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS body_anchor")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS shadow_active")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS core_pattern")
    op.execute("ALTER TABLE IF EXISTS sync_sessions DROP COLUMN IF EXISTS real_picture")
    # ### end Alembic commands ###
